pom.xml, src/main/java/com/nhnacademy/front/adaptor/UserAdaptor.java, src/main/java/com/nhnacademy/front/config/RedisConfig.java, src/main/java/com/nhnacademy/front/controller/LogoutController.java, src/main/java/com/nhnacademy/front/utils/RedisUtil.java
- logout controller 구현
- redis dependency 추가
- redis config 추가
- redis util 클래스 추가
- user adaptor logout 요청 메서드 추가
- black list 추가 로직 구현
=> Feat: 로그아웃 구현 작업

src/main/java/com/nhnacademy/front/config/RedisConfig.java
=> Refactor: redis config 수정

pom.xml, src/main/java/com/nhnacademy/front/config/RabbitmqConfig.java, src/main/java/com/nhnacademy/front/config/RedisConfig.java, src/main/java/com/nhnacademy/front/controller/ControlController.java, src/main/java/com/nhnacademy/front/dto/ValueMessage.java, src/main/java/com/nhnacademy/front/service/RabbitmqService.java, src/main/java/com/nhnacademy/front/service/impl/RabbitmqServiceImpl.java, src/main/java/com/nhnacademy/front/utils/RedisUtil.java, src/main/resources/application.yml, src/main/resources/static/js/controlPage/control.js, src/main/resources/templates/control.html, src/test/java/com/nhnacademy/front/controller/ControlControllerTest.java, src/test/java/com/nhnacademy/front/service/RabbitmqServiceTest.java
- control 페이지 구현
- 조명 제어 구현
- 에어컨 제어 구현
- 공기청정기 제어 구현
- 모드 변경 구현
- test 작성
=> Feat: 장치 제어 페이지 기능 구현

src/main/java/com/nhnacademy/front/adaptor/DeviceSettingAdapter.java, src/main/java/com/nhnacademy/front/config/WebConfig.java, src/main/java/com/nhnacademy/front/controller/DeviceSettingController.java, src/main/java/com/nhnacademy/front/dto/DeviceRequest.java, src/main/java/com/nhnacademy/front/dto/DeviceResponse.java, src/main/java/com/nhnacademy/front/dto/DeviceSensorRequest.java, src/main/java/com/nhnacademy/front/dto/DeviceSensorResponse.java, src/main/java/com/nhnacademy/front/mode/AircleanerMode.java, src/main/resources/templates/aircleaner-setting.html, src/main/resources/templates/fragments/device-tab.html
- DeviceSetting Controller 추가
- Device, DeviceSensor dto 추가
- 공기청정기 enum(모드) 추가
- DeviceSetting FeignClient 추가
- 공기청정기 setting 뷰 추가
=> Feat: aircleaner DeviceSetting 구현

src/main/java/com/nhnacademy/front/adaptor/UserAdapter.java, src/main/java/com/nhnacademy/front/controller/LoginController.java, src/main/java/com/nhnacademy/front/controller/UserController.java, src/main/resources/templates/profile.html, src/test/java/com/nhnacademy/front/controller/LoginControllerTest.java, src/test/java/com/nhnacademy/front/controller/UserControllerTest.java
- 유저 탈퇴 기능 추가
- 관리자에게 승인되지 않은 사용자는 로그인 하지 못하는 기능 추가
=> 유저 탈퇴 기능 추가

src/main/java/com/nhnacademy/front/controller/DeviceSettingController.java, src/main/resources/static/css/temperature-select-style.css, src/main/resources/static/js/device-setting-page/temperature-select-script.js, src/main/resources/templates/device-setting/airconditioner-setting.html, src/main/resources/templates/device-setting/setting-view.html
- 에어컨 설정 페이지 뷰 구현
- 에어컨 설정 페이지 기능 구현
=> Feat: 에어컨 설정 페이지 뷰 및 기능 구현

src/main/java/com/nhnacademy/front/adaptor/DeviceSettingAdapter.java, src/main/java/com/nhnacademy/front/controller/DetectionSettingController.java, src/main/java/com/nhnacademy/front/dto/TimeIntervalRequest.java, src/main/java/com/nhnacademy/front/dto/TimeIntervalResponse.java, src/main/resources/templates/device-setting/aircleaner-setting.html, src/main/resources/templates/device-setting/airconditioner-setting.html, src/main/resources/templates/device-setting/detection-setting.html, src/main/resources/templates/device-setting/light-setting.html, src/main/resources/templates/device-setting/setting-view.html, src/main/resources/templates/fragments/device-tab.html
- DetectionSettingController 구현
- DeviceSettingAdapter에 TimeInterval 관련 기능 추가
- TimeInterval DTO 추가
- device-setting 관련 view 레이아웃 수정
=> Feat: detection-setting 뷰 구현 및 기능 구현

src/main/resources/static/css/userManage/style.css, src/main/resources/templates/manage.html
- 테이블 디자인 변경
- 관리자 조회 페이지에서 선택 제거
=> Refactor: 회원 관리 페이지 디자인 수정

src/main/java/com/nhnacademy/front/controller/AdminController.java, src/main/resources/templates/detailedSensor.html
=> Refactor: 상세 센서 페이지 디자인 수정

src/main/java/com/nhnacademy/front/adaptor/UserAdapter.java, src/main/java/com/nhnacademy/front/controller/AdminController.java, src/main/resources/templates/fragments/user-manage-tab.html, src/main/resources/templates/manage.html
- 관리자 권한 부여 기능 적용 및 코드정리
- 버튼 누른뒤, 현재 페이지 유지 기능 추가
=> 관리자 권한 부여 기능 적용

src/main/java/com/nhnacademy/front/controller/AdminController.java, src/main/resources/templates/detailedSensor.html, src/main/resources/templates/fragments/sidebar.html
- AdminController 에 필요한 model 정보 추가
- view 일부 수정
- 그래프 관련 script refactoring
=> Feat: 상세 센서 정보 장소 구분

src/main/java/com/nhnacademy/front/config/WebConfig.java, src/main/java/com/nhnacademy/front/controller/ControlController.java, src/main/java/com/nhnacademy/front/dto/PlaceResponse.java, src/main/resources/static/js/controlPage/control.js, src/main/resources/templates/control.html, src/main/resources/templates/device-setting/aircleaner-setting.html, src/main/resources/templates/device-setting/airconditioner-setting.html, src/main/resources/templates/device-setting/detection-setting.html, src/main/resources/templates/device-setting/setting-view.html, src/main/resources/templates/fragments/place-tab.html, src/main/resources/templates/fragments/sidebar.html, src/main/resources/templates/fragments/time-interval-setting.html, src/test/java/com/nhnacademy/front/controller/ControlControllerTest.java
- controll-view, setting-view 디자인 수정
- place code 추가
=> Refactor: control-view 및 다른 view 디자인 수정, place code 추가

src/main/java/com/nhnacademy/front/advice/ExceptionAdvice.java, src/main/resources/templates/error.html, src/main/resources/templates/login.html
- Logout advice 수정
- Logout view 수정
- ADMIN Login 추가
=> Refactor: 로그아웃 수정

src/main/java/com/nhnacademy/front/controller/ControlController.java, src/main/java/com/nhnacademy/front/utils/RedisUtil.java, src/main/resources/static/js/controlPage/control.js, src/main/resources/templates/control.html, src/test/java/com/nhnacademy/front/controller/ControlControllerTest.java
- AI mode와 custom mode 분리
- Test 수정
=> Refactor: 장치 제어 페이지 수정

src/main/java/com/nhnacademy/front/config/RedisConfig.java, src/main/java/com/nhnacademy/front/controller/ControlController.java, src/main/java/com/nhnacademy/front/utils/RedisUtil.java, src/main/resources/static/js/controlPage/control.js, src/main/resources/templates/control.html, src/test/java/com/nhnacademy/front/controller/ControlControllerTest.java
- ai 결과 보여주는 Modal 추가
- Test 추가
=> Feat: AI 결과 확인 기능

src/main/resources/static/js/controlPage/control.js, src/main/resources/templates/control.html
- AI Mode가 켜져있을 때만 결과 확인 버튼이 보이게 수정
=> Refactor: ai mode 켜지면 결과 버튼 생기게 변경

src/main/java/com/nhnacademy/front/controller/DeviceSettingController.java, src/main/resources/templates/device-setting/aircleaner-setting.html, src/main/resources/templates/device-setting/airconditioner-setting.html, src/main/resources/templates/device-setting/detection-setting.html, src/main/resources/templates/device-setting/setting-view.html, src/main/resources/templates/fragments/place-tab.html, src/main/resources/templates/fragments/time-interval-setting.html
- Device별 DeviceSensor List로 받기 변경
- 변경 버튼 삭제 및 input disabled 변경
=> Refactor: 설정페이지에서 센서별 설정값 표시 설정

src/main/resources/templates/control.html
=> Chore: 배경 cover 변경

src/main/resources/templates/control.html
=> Chore: aimode 결과버튼 수정

pom.xml, src/main/java/com/nhnacademy/front/interceptor/AddAuthorityToModelInterceptor.java, src/main/resources/templates/device-setting/aircleaner-setting.html, src/main/resources/templates/device-setting/airconditioner-setting.html, src/main/resources/templates/device-setting/detection-setting.html, src/main/resources/templates/device-setting/setting-view.html, src/main/resources/templates/fragments/nav.html, src/main/resources/templates/fragments/sidebar.html, src/main/resources/templates/fragments/time-interval-setting.html
- thymeleaf-springsecurity 적용
- addAuthorityToModel 에 model 추가부분 삭제
- sec:authority 적용
- 뷰 디자인 수정
=> Refactor: thymeleaf-springsecurity 적용

pom.xml, src/main/java/com/nhnacademy/front/controller/LoginController.java, src/main/java/com/nhnacademy/front/dto/LoginRequest.java, src/main/java/com/nhnacademy/front/dto/UserRegisterRequest.java, src/main/java/com/nhnacademy/front/utils/RedisUtil.java, src/main/resources/static/js/controlPage/control.js
- dto validation 조건 추가
- redis 기본값 반환 추가
- 인공지능 예측 결과 기본값 추가
=> Feat: validation 추가

src/main/java/com/nhnacademy/front/utils/RedisUtil.java
=> Refactor: 장치 상태 기본값 수정
